modLoader="javafml"
loaderVersion="[${loader_version},)"
license="All rights reserved"
issueTrackerURL="https://github.com/Flemmli97/MobBattle/issues"
[[mods]]
modId="mobbattle"
version="${version}"
displayName="Mob Battle Mod"
displayURL="${homepage}"
logoFile="icon.png"
authors="Flemmli97"
description='''Creative utensils in creating spectacular mob battles'''
[[dependencies.mobbattle]]
modId="minecraft"
mandatory=true
versionRange="[${mcversion},)"
ordering="NONE"
side="BOTH"
[[dependencies.mobbattle]]
modId="forge"
mandatory=true
versionRange="[${forge_version},)"
ordering="NONE"
side="BOTH"
