modLoader="javafml"
loaderVersion="[38,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Flemmli97/MobBattle/issues"
[[mods]]
modId="mobbattle"
version="${version}"
displayName="Mob Battle Mod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/mob-battle-mod"
logoFile="icon.png"
authors="Flemmli97"
description='''Creative utensils in creating spectacular mob battles'''
[[dependencies.mobbattle]]
modId="minecraft"
mandatory=true
versionRange="[1.18,)"
ordering="NONE"
side="BOTH"
[[dependencies.mobbattle]]
modId="tenshilib"
mandatory=false
versionRange="[1.18.1-1.5.0,)"
ordering="NONE"
side="BOTH"