modLoader="javafml"
loaderVersion="[41,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Flemmli97/MobBattle/issues"
[[mods]]
modId="mobbattle"
version="${version}"
displayName="Mob Battle Mod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/mob-battle-mod"
logoFile="icon.png"
authors="Flemmli97"
description='''Creative utensils in creating spectacular mob battles'''
[[dependencies.mobbattle]]
modId="minecraft"
mandatory=true
versionRange="[1.19,)"
ordering="NONE"
side="BOTH"
[[dependencies.mobbattle]]
modId="forge"
mandatory=true
versionRange="[41.1.0,)"
ordering="NONE"
side="BOTH"
