plugins {
    id 'net.fabricmc.fabric-loom' version '1.15-SNAPSHOT' apply false
    id 'net.neoforged.moddev' version '2.0.141' apply false
    id 'io.github.flemmli97.multiloader.discord_hook' version '2.+'
}

subprojects {
    repositories {
        maven {
            name = "TenshiLib"
            url "https://maven.blazing-coop.net/releases"
            content {
                includeGroup 'io.github.flemmli97'
            }
        }
    }
}