org.gradle.jvmargs=-Xmx3G
jvm=25
minecraft_version=26.1.2
neoForm_version=26.1.2-1
# NeoForge Properties
neoforge_version=26.1.2.30-beta
# Fabric Properties
fabric_loader_version=0.16.14

# Mod Properties
mod_version=2.7.1
maven_group=io.github.flemmli97
mod_id=mobbattle
mod_author=flemmli97

# Dependencies
fabric_api_version=0.147.0+26.1.2
tenshilib_dep=io.github.flemmli97:tenshilib:1.21.1-2.0.0

# Curse properties
curseforge_versions=26.1.2, Java 25
curseforge_page_fabric=https://www.curseforge.com/minecraft/mc-mods/mob-battle-mod-fabric
curseforge_id_fabric=552316
curseforge_dep_fabric=fabric-api
curseforge_page_neoforge=https://www.curseforge.com/minecraft/mc-mods/mob-battle-mod
curseforge_id_neoforge=268746
curseforge_dep_neoforge=
modrinth_versions=26.1.2
modrinth_page=https://modrinth.com/mod/mob-battle-mod
modrinth_id=LbrJcAlI
modrinth_dep_fabric=fabric-api
modrinth_dep_neoforge=

# Other
project_name=Mob Battle
full_changelog=https://github.com/Flemmli97/MobBattle/blob/26.1/Changelog.md
discord_role=852113514692214794
