modLoader="javafml"
loaderVersion="[28,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Flemmli97/MobBattle/issues"
displayURL="https://github.com/Flemmli97/MobBattle"
# logoFile=""
credits=""
authors="Flemmli97"
[[mods]] 
  modId="mobbattle"
  version="${file.jarVersion}"
  displayName="Mob Battle Mod"
  # updateJSONURL=""
  authors="Flemmli97"
  description='''Creative utensils in creating spectacular mob battles'''
[[dependencies.mobbattle]]
  modId="minecraft"
  mandatory=true
  versionRange="[1.16.2,)"
  ordering="NONE"
  side="BOTH"
[[dependencies.mobbattle]]
  modId="tenshilib"
  mandatory=false
  versionRange="[1.0,)"
  ordering="NONE"
  side="BOTH"